server:
  port: 8090

thymeleaf:
  mode: LEGACYHTML5
  encoding: UTF-8
  content-type: text/html
  #开发时关闭缓存,不然没法看到实时页面
  cache: false

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
     com.yjhy.mapper : debug





